---
- hosts: web

  vars:
    http_port: 80

  user: ubuntu


  tasks:
  - name: install nginx
    apt: name=nginx state=present

  - name: ensure nginx is running
    service: name=nginx state=running

  - name: wait for nginx to be running
    wait_for: port={{ http_port  }} delay=3
